Feature/weos 984
wepala/weos-crm-api pull request #38
Opened 2021-05-20 18:55 UTC by EmmanuelSammy

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Adds E2E tests for updating request types and adds get request type calls.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-05-24 21:32 UTC, akeemphilbert requested changes

2021-05-24 21:32 UTC, akeemphilbert commented on src/api.go
> +	//setup fileters
small typo here

2021-05-24 21:32 UTC, akeemphilbert commented on src/api.go
> +	// Check for existing titles
The command should be responsible for this. This should not be happening here

2021-05-25 15:16 UTC, EmmanuelSammy commented on src/api.go
> +	// Check for existing titles
okay noted

2021-05-25 17:14 UTC, akeemphilbert approved these changes

2021-05-25 17:16 UTC, merged