Feature/weos 1041
wepala/weos-crm-api pull request #40
Opened 2021-05-24 18:40 UTC by EmmanuelSammy

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Gets Additional Fields to be saved as json in the db
- Return Additional Field db data into struct for data to be returned

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-05-24 21:44 UTC, akeemphilbert requested changes

2021-05-24 21:44 UTC, akeemphilbert commented on src/api.go
> +	if requestType.Title != "" {
This check should not be here. This should be handled by the module

2021-05-24 21:44 UTC, akeemphilbert commented on src/gorm_projection.go
> +func (c *GORMProjection) GetCRMRequestTypeByID(id string) (*RequestType, error) {
why is "CRM" in the method name?

2021-05-25 16:30 UTC, EmmanuelSammy commented on src/gorm_projection.go
> +func (c *GORMProjection) GetCRMRequestTypeByID(id string) (*RequestType, error) {
Due to the different structs associated (crm/module) the crm one returns the crm or projection struct so that simon doesnt have any issues

2021-05-25 17:11 UTC, akeemphilbert approved these changes

2021-05-25 17:44 UTC, merged