Feature/weos 1052
wepala/weos-crm-api pull request #49
Opened 2021-06-01 18:43 UTC by EmmanuelSammy

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Adds E2E tests for creating a request.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-06-01 18:52 UTC, akeemphilbert requested changes

2021-06-01 18:52 UTC, akeemphilbert commented on api.yaml
> +        requestTasks:
why is it called requestTasks and not simply tasks?

2021-06-02 13:50 UTC, EmmanuelSammy commented on api.yaml
> +        requestTasks:
thats just what we use as the json tag in the payload atonia has the payload different from the entity due to some marshalling things or something of the sort.

2021-06-02 14:07 UTC, atoniaw commented on api.yaml
> +        requestTasks:
Because the tasks field is a map on the request, if they both have the same json tag, it'll attempt to unmarshal the array into the map and cause an error.

2021-06-02 14:07 UTC, atoniaw submitted a review, later dismissed

2021-06-02 14:13 UTC, atoniaw commented on server.go
> +var port = flag.String("port", "3000", "-port=3000")
change the ports back

2021-06-02 15:33 UTC, atoniaw approved these changes

2021-06-02 17:24 UTC, akeemphilbert approved these changes

2021-06-02 17:25 UTC, merged